platform :ios, '7.0'

inhibit_all_warnings!

abstract_target ‘YE’ do

pod 'MJExtension'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'IQKeyboardManager'
pod 'YTKNetwork'
pod 'DZNEmptyDataSet'
pod 'SDCycleScrollView'
pod 'TOWebViewController'
pod 'Masonry', '~> 1.0.1'
pod 'UMengAnalytics'    #标准SDK，含IDFA

target ‘IRSystem’

end